apiVersion: v1
data:
  extension.config: |
    extensions:
    - name: metrics
      backend:
        services:
        - url: http://argocd-metrics-server.metrics-server.svc.cluster.local:9003    
    - name: logsummary
      backend:
        services:
        - url: http://log-summarization-service.dev-log-usw2-dev.svc.cluster.local:8080
    
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd