apiVersion: v1
kind: Service
metadata:
  name: numaproj-assist-backend-service
  namespace: numaproj-assist
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: numaproj-assist-backend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: numaproj-assist-backend-service
  name: numaproj-assist-backend-service
  namespace: numaproj-assist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: numaproj-assist-backend-service
  template:
    metadata:
      labels:
        app: numaproj-assist-backend-service
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: isbsvc-log-summarization-redis-svc:26379
        - name: REDIS_MASTERNAME
          value: mymaster
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: isbsvc-log-summarization-redis-auth
        image: quay.io/numaio/numaproj-assist-backend-service:latest
        imagePullPolicy: Always
        name: log
        ports:
        - containerPort: 8080
